### ISSUE TITLE
Idea: color coded blocks on rating + time lapsed  (posted on discussions)

### ISSUE THREAD

**Issue by Cybeuu** [earcherc/deep-work#10]
![image](https://github.com/user-attachments/assets/5e281e1f-7f19-4bce-a8c5-b93320af74a6)

deep work rating = color depth of deep work block

and user can write short bullet comments about their deep work sesh.

short and bullet to make it compact but also to force user to think of that one thing resulting in low/high rating rather than a whole story.

also, a simple time lapse could also be placed beside the deep work time log (5 h 30min as shown in pic above)

**Comment by earcherc** [comment]
Awesome! 

Thanks @Cybeuu 

I will get this in on the weekend

**Comment by Cybeuu** [comment]
I'm excited! thank you, im glad you liked it❤️
